events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /login {
            proxy_pass http://auth_server:4000/login;
            proxy_set_header Host $host;
        }

        location /auth {
            proxy_pass http://auth_server:4000/auth;
            proxy_set_header Host $host;
        }

        location /check {
            internal;
            proxy_pass http://auth_server:4000/check;
            proxy_set_header Cookie $http_cookie;
        }

        location /signal/ {
            proxy_pass http://signal_server:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
        }

        location /socket.io/ {
            proxy_pass http://anon_chat:80/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
        }

        location / {
            auth_request /check;
            error_page 401 = @login_redirect;

            proxy_pass http://anon_chat:80/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            client_max_body_size 50M;
        }

        location @login_redirect {
            return 302 /login;
        }
    }
}
