events { worker_connections 1024; }

http {
    server_tokens off;
    server {
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer" always;
        listen 80;

        location / {
            proxy_pass http://pschat:80/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header Cookie $http_cookie;
            proxy_read_timeout 3600s;
            client_max_body_size 50M;
        }
    }
}
